
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: Alpachino123
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
