
# Config BD
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: Alpachino123
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect

# Config JWT

security:
  jwt:
    secret-key: "3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b"
    expiration-time: 3600000 # 1h in milliseconds
