--CREATE SCHEMA
CREATE USER jwt_security IDENTIFIED BY 1;


--CREATE APP
--PERMISOS
ALTER USER jwt_security QUOTA UNLIMITED ON USERS;

--USER CREATION
INSERT INTO JWT_SECURITY.USERS(ID, FULL_NAME, EMAIL, PASSWORD, CREATED_AT, UPDATED_AT)
VALUES (1, 'user', 'user@example.com', 'secret', SYSDATE, SYSDATE);